
path: C:/Users/miche/Desktop/Projects/CatDetector/Dataset # absolute path dataset
train: images/train # train images(relative to "path")
val: images/val # val images (relative to "path")

# Classes, diverse classi da rilevare nelle immagini
nc: 1
names:
  0: cat